<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();
        
        $cities = [
            // 1. Acre (AC)
            ['state_id' => 1, 'name' => 'Rio Branco'],
            ['state_id' => 1, 'name' => 'Cruzeiro do Sul'],
            ['state_id' => 1, 'name' => 'Sena Madureira'],
            ['state_id' => 1, 'name' => 'Tarauacá'],
            ['state_id' => 1, 'name' => 'Feijó'],
            ['state_id' => 1, 'name' => 'Xapuri'],
            ['state_id' => 1, 'name' => 'Plácido de Castro'],
            ['state_id' => 1, 'name' => 'Mâncio Lima'],
            ['state_id' => 1, 'name' => 'Epitaciolândia'],
            ['state_id' => 1, 'name' => 'Rodrigues Alves'],
            ['state_id' => 1, 'name' => 'Marechal Thaumaturgo'],
            ['state_id' => 1, 'name' => 'Porto Acre'],
            ['state_id' => 1, 'name' => 'Acrelândia'],
            ['state_id' => 1, 'name' => 'Bujari'],
            ['state_id' => 1, 'name' => 'Capixaba'],
            ['state_id' => 1, 'name' => 'Jordão'],
            ['state_id' => 1, 'name' => 'Manoel Urbano'],
            ['state_id' => 1, 'name' => 'Porto Walter'],
            ['state_id' => 1, 'name' => 'Santa Rosa do Purus'],
            ['state_id' => 1, 'name' => 'Assis Brasil'],

            // 2. Alagoas (AL)
            ['state_id' => 2, 'name' => 'Maceió'],
            ['state_id' => 2, 'name' => 'Arapiraca'],
            ['state_id' => 2, 'name' => 'Rio Largo'],
            ['state_id' => 2, 'name' => 'Palmeira dos Índios'],
            ['state_id' => 2, 'name' => 'União dos Palmares'],
            ['state_id' => 2, 'name' => 'Penedo'],
            ['state_id' => 2, 'name' => 'São Miguel dos Campos'],
            ['state_id' => 2, 'name' => 'Campo Alegre'],
            ['state_id' => 2, 'name' => 'Coruripe'],
            ['state_id' => 2, 'name' => 'Marechal Deodoro'],
            ['state_id' => 2, 'name' => 'Delmiro Gouveia'],
            ['state_id' => 2, 'name' => 'Santana do Ipanema'],
            ['state_id' => 2, 'name' => 'Atalaia'],
            ['state_id' => 2, 'name' => 'Teotônio Vilela'],
            ['state_id' => 2, 'name' => 'Girau do Ponciano'],
            ['state_id' => 2, 'name' => 'Pilar'],
            ['state_id' => 2, 'name' => 'São Luís do Quitunde'],
            ['state_id' => 2, 'name' => 'São Sebastião'],
            ['state_id' => 2, 'name' => 'Maragogi'],
            ['state_id' => 2, 'name' => 'Viçosa'],

            // 3. Amapá (AP)
            ['state_id' => 3, 'name' => 'Macapá'],
            ['state_id' => 3, 'name' => 'Santana'],
            ['state_id' => 3, 'name' => 'Laranjal do Jari'],
            ['state_id' => 3, 'name' => 'Oiapoque'],
            ['state_id' => 3, 'name' => 'Mazagão'],
            ['state_id' => 3, 'name' => 'Porto Grande'],
            ['state_id' => 3, 'name' => 'Tartarugalzinho'],
            ['state_id' => 3, 'name' => 'Pedra Branca do Amapari'],
            ['state_id' => 3, 'name' => 'Vitória do Jari'],
            ['state_id' => 3, 'name' => 'Calçoene'],
            ['state_id' => 3, 'name' => 'Amapá'],
            ['state_id' => 3, 'name' => 'Ferreira Gomes'],
            ['state_id' => 3, 'name' => 'Cutias'],
            ['state_id' => 3, 'name' => 'Itaubal'],
            ['state_id' => 3, 'name' => 'Pracuúba'],
            ['state_id' => 3, 'name' => 'Serra do Navio'],

            // 4. Amazonas (AM)
            ['state_id' => 4, 'name' => 'Manaus'],
            ['state_id' => 4, 'name' => 'Parintins'],
            ['state_id' => 4, 'name' => 'Itacoatiara'],
            ['state_id' => 4, 'name' => 'Manacapuru'],
            ['state_id' => 4, 'name' => 'Coari'],
            ['state_id' => 4, 'name' => 'Tabatinga'],
            ['state_id' => 4, 'name' => 'Maués'],
            ['state_id' => 4, 'name' => 'Tefé'],
            ['state_id' => 4, 'name' => 'Manicoré'],
            ['state_id' => 4, 'name' => 'Humaitá'],
            ['state_id' => 4, 'name' => 'Iranduba'],
            ['state_id' => 4, 'name' => 'Lábrea'],
            ['state_id' => 4, 'name' => 'São Gabriel da Cachoeira'],
            ['state_id' => 4, 'name' => 'Benjamin Constant'],
            ['state_id' => 4, 'name' => 'Borba'],
            ['state_id' => 4, 'name' => 'Autazes'],
            ['state_id' => 4, 'name' => 'São Paulo de Olivença'],
            ['state_id' => 4, 'name' => 'Careiro'],
            ['state_id' => 4, 'name' => 'Nova Olinda do Norte'],
            ['state_id' => 4, 'name' => 'Presidente Figueiredo'],

            // 5. Bahia (BA)
            ['state_id' => 5, 'name' => 'Salvador'],
            ['state_id' => 5, 'name' => 'Feira de Santana'],
            ['state_id' => 5, 'name' => 'Vitória da Conquista'],
            ['state_id' => 5, 'name' => 'Camaçari'],
            ['state_id' => 5, 'name' => 'Juazeiro'],
            ['state_id' => 5, 'name' => 'Itabuna'],
            ['state_id' => 5, 'name' => 'Lauro de Freitas'],
            ['state_id' => 5, 'name' => 'Ilhéus'],
            ['state_id' => 5, 'name' => 'Jequié'],
            ['state_id' => 5, 'name' => 'Teixeira de Freitas'],
            ['state_id' => 5, 'name' => 'Barreiras'],
            ['state_id' => 5, 'name' => 'Alagoinhas'],
            ['state_id' => 5, 'name' => 'Porto Seguro'],
            ['state_id' => 5, 'name' => 'Simões Filho'],
            ['state_id' => 5, 'name' => 'Paulo Afonso'],
            ['state_id' => 5, 'name' => 'Eunápolis'],
            ['state_id' => 5, 'name' => 'Santo Antônio de Jesus'],
            ['state_id' => 5, 'name' => 'Valença'],
            ['state_id' => 5, 'name' => 'Candeias'],
            ['state_id' => 5, 'name' => 'Guanambi'],

            // 6. Ceará (CE)
            ['state_id' => 6, 'name' => 'Fortaleza'],
            ['state_id' => 6, 'name' => 'Caucaia'],
            ['state_id' => 6, 'name' => 'Juazeiro do Norte'],
            ['state_id' => 6, 'name' => 'Maracanaú'],
            ['state_id' => 6, 'name' => 'Sobral'],
            ['state_id' => 6, 'name' => 'Crato'],
            ['state_id' => 6, 'name' => 'Itapipoca'],
            ['state_id' => 6, 'name' => 'Maranguape'],
            ['state_id' => 6, 'name' => 'Iguatu'],
            ['state_id' => 6, 'name' => 'Quixadá'],
            ['state_id' => 6, 'name' => 'Pacatuba'],
            ['state_id' => 6, 'name' => 'Aquiraz'],
            ['state_id' => 6, 'name' => 'Quixeramobim'],
            ['state_id' => 6, 'name' => 'Canindé'],
            ['state_id' => 6, 'name' => 'Russas'],
            ['state_id' => 6, 'name' => 'Crateús'],
            ['state_id' => 6, 'name' => 'Tianguá'],
            ['state_id' => 6, 'name' => 'Aracati'],
            ['state_id' => 6, 'name' => 'Cascavel'],
            ['state_id' => 6, 'name' => 'Pacajus'],

            // 7. Distrito Federal (DF)
            ['state_id' => 7, 'name' => 'Brasília'],
            ['state_id' => 7, 'name' => 'Ceilândia'],
            ['state_id' => 7, 'name' => 'Samambaia'],
            ['state_id' => 7, 'name' => 'Taguatinga'],
            ['state_id' => 7, 'name' => 'Plano Piloto'],
            ['state_id' => 7, 'name' => 'Planaltina'],
            ['state_id' => 7, 'name' => 'Águas Claras'],
            ['state_id' => 7, 'name' => 'Recanto das Emas'],
            ['state_id' => 7, 'name' => 'Gama'],
            ['state_id' => 7, 'name' => 'Guará'],
            ['state_id' => 7, 'name' => 'Santa Maria'],
            ['state_id' => 7, 'name' => 'Sobradinho'],
            ['state_id' => 7, 'name' => 'São Sebastião'],
            ['state_id' => 7, 'name' => 'Vicente Pires'],
            ['state_id' => 7, 'name' => 'Itapoã'],
            ['state_id' => 7, 'name' => 'Sobradinho II'],
            ['state_id' => 7, 'name' => 'Sudoeste/Octogonal'],
            ['state_id' => 7, 'name' => 'Brazlândia'],
            ['state_id' => 7, 'name' => 'Riacho Fundo'],
            ['state_id' => 7, 'name' => 'Paranoá'],

            // 8. Espírito Santo (ES)
            ['state_id' => 8, 'name' => 'Serra'],
            ['state_id' => 8, 'name' => 'Vila Velha'],
            ['state_id' => 8, 'name' => 'Cariacica'],
            ['state_id' => 8, 'name' => 'Vitória'],
            ['state_id' => 8, 'name' => 'Cachoeiro de Itapemirim'],
            ['state_id' => 8, 'name' => 'Linhares'],
            ['state_id' => 8, 'name' => 'São Mateus'],
            ['state_id' => 8, 'name' => 'Guarapari'],
            ['state_id' => 8, 'name' => 'Colatina'],
            ['state_id' => 8, 'name' => 'Aracruz'],
            ['state_id' => 8, 'name' => 'Viana'],
            ['state_id' => 8, 'name' => 'Nova Venécia'],
            ['state_id' => 8, 'name' => 'Barra de São Francisco'],
            ['state_id' => 8, 'name' => 'Santa Maria de Jetibá'],
            ['state_id' => 8, 'name' => 'Marataízes'],
            ['state_id' => 8, 'name' => 'Castelo'],
            ['state_id' => 8, 'name' => 'São Gabriel da Palha'],
            ['state_id' => 8, 'name' => 'Domingos Martins'],
            ['state_id' => 8, 'name' => 'Itapemirim'],
            ['state_id' => 8, 'name' => 'Afonso Cláudio'],

            // 9. Goiás (GO)
            ['state_id' => 9, 'name' => 'Goiânia'],
            ['state_id' => 9, 'name' => 'Aparecida de Goiânia'],
            ['state_id' => 9, 'name' => 'Anápolis'],
            ['state_id' => 9, 'name' => 'Rio Verde'],
            ['state_id' => 9, 'name' => 'Águas Lindas de Goiás'],
            ['state_id' => 9, 'name' => 'Luziânia'],
            ['state_id' => 9, 'name' => 'Valparaíso de Goiás'],
            ['state_id' => 9, 'name' => 'Trindade'],
            ['state_id' => 9, 'name' => 'Formosa'],
            ['state_id' => 9, 'name' => 'Novo Gama'],
            ['state_id' => 9, 'name' => 'Senador Canedo'],
            ['state_id' => 9, 'name' => 'Catalão'],
            ['state_id' => 9, 'name' => 'Itumbiara'],
            ['state_id' => 9, 'name' => 'Jataí'],
            ['state_id' => 9, 'name' => 'Caldas Novas'],
            ['state_id' => 9, 'name' => 'Planaltina'],
            ['state_id' => 9, 'name' => 'Santo Antônio do Descoberto'],
            ['state_id' => 9, 'name' => 'Cidade Ocidental'],
            ['state_id' => 9, 'name' => 'Goianésia'],
            ['state_id' => 9, 'name' => 'Mineiros'],

            // 10. Maranhão (MA)
            ['state_id' => 10, 'name' => 'São Luís'],
            ['state_id' => 10, 'name' => 'Imperatriz'],
            ['state_id' => 10, 'name' => 'São José de Ribamar'],
            ['state_id' => 10, 'name' => 'Timon'],
            ['state_id' => 10, 'name' => 'Caxias'],
            ['state_id' => 10, 'name' => 'Paço do Lumiar'],
            ['state_id' => 10, 'name' => 'Codó'],
            ['state_id' => 10, 'name' => 'Açailândia'],
            ['state_id' => 10, 'name' => 'Bacabal'],
            ['state_id' => 10, 'name' => 'Balsas'],
            ['state_id' => 10, 'name' => 'Santa Inês'],
            ['state_id' => 10, 'name' => 'Barra do Corda'],
            ['state_id' => 10, 'name' => 'Pinheiro'],
            ['state_id' => 10, 'name' => 'Chapadinha'],
            ['state_id' => 10, 'name' => 'Buriticupu'],
            ['state_id' => 10, 'name' => 'Grajaú'],
            ['state_id' => 10, 'name' => 'Itapecuru Mirim'],
            ['state_id' => 10, 'name' => 'Coroatá'],
            ['state_id' => 10, 'name' => 'Barreirinhas'],
            ['state_id' => 10, 'name' => 'Tutóia'],

            // 11. Mato Grosso (MT)
            ['state_id' => 11, 'name' => 'Cuiabá'],
            ['state_id' => 11, 'name' => 'Várzea Grande'],
            ['state_id' => 11, 'name' => 'Rondonópolis'],
            ['state_id' => 11, 'name' => 'Sinop'],
            ['state_id' => 11, 'name' => 'Tangará da Serra'],
            ['state_id' => 11, 'name' => 'Cáceres'],
            ['state_id' => 11, 'name' => 'Sorriso'],
            ['state_id' => 11, 'name' => 'Lucas do Rio Verde'],
            ['state_id' => 11, 'name' => 'Primavera do Leste'],
            ['state_id' => 11, 'name' => 'Barra do Garças'],
            ['state_id' => 11, 'name' => 'Alta Floresta'],
            ['state_id' => 11, 'name' => 'Pontes e Lacerda'],
            ['state_id' => 11, 'name' => 'Nova Mutum'],
            ['state_id' => 11, 'name' => 'Juína'],
            ['state_id' => 11, 'name' => 'Campo Novo do Parecis'],
            ['state_id' => 11, 'name' => 'Juara'],
            ['state_id' => 11, 'name' => 'Peixoto de Azevedo'],
            ['state_id' => 11, 'name' => 'Poconé'],
            ['state_id' => 11, 'name' => 'Colniza'],
            ['state_id' => 11, 'name' => 'Guarantã do Norte'],

            // 12. Mato Grosso do Sul (MS)
            ['state_id' => 12, 'name' => 'Campo Grande'],
            ['state_id' => 12, 'name' => 'Dourados'],
            ['state_id' => 12, 'name' => 'Três Lagoas'],
            ['state_id' => 12, 'name' => 'Corumbá'],
            ['state_id' => 12, 'name' => 'Ponta Porã'],
            ['state_id' => 12, 'name' => 'Sidrolândia'],
            ['state_id' => 12, 'name' => 'Naviraí'],
            ['state_id' => 12, 'name' => 'Nova Andradina'],
            ['state_id' => 12, 'name' => 'Aquidauana'],
            ['state_id' => 12, 'name' => 'Maracaju'],
            ['state_id' => 12, 'name' => 'Paranaíba'],
            ['state_id' => 12, 'name' => 'Amambai'],
            ['state_id' => 12, 'name' => 'Rio Brilhante'],
            ['state_id' => 12, 'name' => 'Coxim'],
            ['state_id' => 12, 'name' => 'Caarapó'],
            ['state_id' => 12, 'name' => 'Miranda'],
            ['state_id' => 12, 'name' => 'São Gabriel do Oeste'],
            ['state_id' => 12, 'name' => 'Jardim'],
            ['state_id' => 12, 'name' => 'Aparecida do Taboado'],
            ['state_id' => 12, 'name' => 'Chapadão do Sul'],

            // 13. Minas Gerais (MG)
            ['state_id' => 13, 'name' => 'Belo Horizonte'],
            ['state_id' => 13, 'name' => 'Uberlândia'],
            ['state_id' => 13, 'name' => 'Contagem'],
            ['state_id' => 13, 'name' => 'Juiz de Fora'],
            ['state_id' => 13, 'name' => 'Betim'],
            ['state_id' => 13, 'name' => 'Montes Claros'],
            ['state_id' => 13, 'name' => 'Ribeirão das Neves'],
            ['state_id' => 13, 'name' => 'Uberaba'],
            ['state_id' => 13, 'name' => 'Governador Valadares'],
            ['state_id' => 13, 'name' => 'Ipatinga'],
            ['state_id' => 13, 'name' => 'Sete Lagoas'],
            ['state_id' => 13, 'name' => 'Divinópolis'],
            ['state_id' => 13, 'name' => 'Santa Luzia'],
            ['state_id' => 13, 'name' => 'Ibirité'],
            ['state_id' => 13, 'name' => 'Poços de Caldas'],
            ['state_id' => 13, 'name' => 'Patos de Minas'],
            ['state_id' => 13, 'name' => 'Pouso Alegre'],
            ['state_id' => 13, 'name' => 'Teófilo Otoni'],
            ['state_id' => 13, 'name' => 'Barbacena'],
            ['state_id' => 13, 'name' => 'Sabará'],

            // 14. Pará (PA)
            ['state_id' => 14, 'name' => 'Belém'],
            ['state_id' => 14, 'name' => 'Ananindeua'],
            ['state_id' => 14, 'name' => 'Santarém'],
            ['state_id' => 14, 'name' => 'Marabá'],
            ['state_id' => 14, 'name' => 'Parauapebas'],
            ['state_id' => 14, 'name' => 'Castanhal'],
            ['state_id' => 14, 'name' => 'Abaetetuba'],
            ['state_id' => 14, 'name' => 'Cametá'],
            ['state_id' => 14, 'name' => 'Marituba'],
            ['state_id' => 14, 'name' => 'Bragança'],
            ['state_id' => 14, 'name' => 'São Félix do Xingu'],
            ['state_id' => 14, 'name' => 'Barcarena'],
            ['state_id' => 14, 'name' => 'Altamira'],
            ['state_id' => 14, 'name' => 'Tucuruí'],
            ['state_id' => 14, 'name' => 'Paragominas'],
            ['state_id' => 14, 'name' => 'Tailândia'],
            ['state_id' => 14, 'name' => 'Breves'],
            ['state_id' => 14, 'name' => 'Itaituba'],
            ['state_id' => 14, 'name' => 'Redenção'],
            ['state_id' => 14, 'name' => 'Moju'],

            // 15. Paraíba (PB)
            ['state_id' => 15, 'name' => 'João Pessoa'],
            ['state_id' => 15, 'name' => 'Campina Grande'],
            ['state_id' => 15, 'name' => 'Santa Rita'],
            ['state_id' => 15, 'name' => 'Patos'],
            ['state_id' => 15, 'name' => 'Bayeux'],
            ['state_id' => 15, 'name' => 'Sousa'],
            ['state_id' => 15, 'name' => 'Cabedelo'],
            ['state_id' => 15, 'name' => 'Cajazeiras'],
            ['state_id' => 15, 'name' => 'Guarabira'],
            ['state_id' => 15, 'name' => 'Sapé'],
            ['state_id' => 15, 'name' => 'Queimadas'],
            ['state_id' => 15, 'name' => 'Mamanguape'],
            ['state_id' => 15, 'name' => 'Pombal'],
            ['state_id' => 15, 'name' => 'Monteiro'],
            ['state_id' => 15, 'name' => 'São Bento'],
            ['state_id' => 15, 'name' => 'Catolé do Rocha'],
            ['state_id' => 15, 'name' => 'Esperança'],
            ['state_id' => 15, 'name' => 'Lagoa Seca'],
            ['state_id' => 15, 'name' => 'Solânea'],
            ['state_id' => 15, 'name' => 'Itaporanga'],

            // 16. Paraná (PR)
            ['state_id' => 16, 'name' => 'Curitiba'],
            ['state_id' => 16, 'name' => 'Londrina'],
            ['state_id' => 16, 'name' => 'Maringá'],
            ['state_id' => 16, 'name' => 'Ponta Grossa'],
            ['state_id' => 16, 'name' => 'Cascavel'],
            ['state_id' => 16, 'name' => 'São José dos Pinhais'],
            ['state_id' => 16, 'name' => 'Foz do Iguaçu'],
            ['state_id' => 16, 'name' => 'Colombo'],
            ['state_id' => 16, 'name' => 'Guarapuava'],
            ['state_id' => 16, 'name' => 'Paranaguá'],
            ['state_id' => 16, 'name' => 'Araucária'],
            ['state_id' => 16, 'name' => 'Toledo'],
            ['state_id' => 16, 'name' => 'Apucarana'],
            ['state_id' => 16, 'name' => 'Pinhais'],
            ['state_id' => 16, 'name' => 'Campo Largo'],
            ['state_id' => 16, 'name' => 'Arapongas'],
            ['state_id' => 16, 'name' => 'Almirante Tamandaré'],
            ['state_id' => 16, 'name' => 'Piraquara'],
            ['state_id' => 16, 'name' => 'Umuarama'],
            ['state_id' => 16, 'name' => 'Cambé'],

            // 17. Pernambuco (PE)
            ['state_id' => 17, 'name' => 'Recife'],
            ['state_id' => 17, 'name' => 'Jaboatão dos Guararapes'],
            ['state_id' => 17, 'name' => 'Olinda'],
            ['state_id' => 17, 'name' => 'Caruaru'],
            ['state_id' => 17, 'name' => 'Petrolina'],
            ['state_id' => 17, 'name' => 'Paulista'],
            ['state_id' => 17, 'name' => 'Cabo de Santo Agostinho'],
            ['state_id' => 17, 'name' => 'Camaragibe'],
            ['state_id' => 17, 'name' => 'Garanhuns'],
            ['state_id' => 17, 'name' => 'Vitória de Santo Antão'],
            ['state_id' => 17, 'name' => 'Igarassu'],
            ['state_id' => 17, 'name' => 'São Lourenço da Mata'],
            ['state_id' => 17, 'name' => 'Santa Cruz do Capibaribe'],
            ['state_id' => 17, 'name' => 'Abreu e Lima'],
            ['state_id' => 17, 'name' => 'Ipojuca'],
            ['state_id' => 17, 'name' => 'Serra Talhada'],
            ['state_id' => 17, 'name' => 'Araripina'],
            ['state_id' => 17, 'name' => 'Gravatá'],
            ['state_id' => 17, 'name' => 'Carpina'],
            ['state_id' => 17, 'name' => 'Goiana'],

            // 18. Piauí (PI)
            ['state_id' => 18, 'name' => 'Teresina'],
            ['state_id' => 18, 'name' => 'Parnaíba'],
            ['state_id' => 18, 'name' => 'Picos'],
            ['state_id' => 18, 'name' => 'Piripiri'],
            ['state_id' => 18, 'name' => 'Floriano'],
            ['state_id' => 18, 'name' => 'Barras'],
            ['state_id' => 18, 'name' => 'Campo Maior'],
            ['state_id' => 18, 'name' => 'União'],
            ['state_id' => 18, 'name' => 'Altos'],
            ['state_id' => 18, 'name' => 'Esperantina'],
            ['state_id' => 18, 'name' => 'José de Freitas'],
            ['state_id' => 18, 'name' => 'Pedro II'],
            ['state_id' => 18, 'name' => 'Oeiras'],
            ['state_id' => 18, 'name' => 'São Raimundo Nonato'],
            ['state_id' => 18, 'name' => 'Miguel Alves'],
            ['state_id' => 18, 'name' => 'Luís Correia'],
            ['state_id' => 18, 'name' => 'Piracuruca'],
            ['state_id' => 18, 'name' => 'Cocal'],
            ['state_id' => 18, 'name' => 'Batalha'],
            ['state_id' => 18, 'name' => 'Corrente'],

            // 19. Rio de Janeiro (RJ)
            ['state_id' => 19, 'name' => 'Rio de Janeiro'],
            ['state_id' => 19, 'name' => 'São Gonçalo'],
            ['state_id' => 19, 'name' => 'Duque de Caxias'],
            ['state_id' => 19, 'name' => 'Nova Iguaçu'],
            ['state_id' => 19, 'name' => 'Niterói'],
            ['state_id' => 19, 'name' => 'Belford Roxo'],
            ['state_id' => 19, 'name' => 'Campos dos Goytacazes'],
            ['state_id' => 19, 'name' => 'São João de Meriti'],
            ['state_id' => 19, 'name' => 'Petrópolis'],
            ['state_id' => 19, 'name' => 'Volta Redonda'],
            ['state_id' => 19, 'name' => 'Magé'],
            ['state_id' => 19, 'name' => 'Macaé'],
            ['state_id' => 19, 'name' => 'Itaboraí'],
            ['state_id' => 19, 'name' => 'Cabo Frio'],
            ['state_id' => 19, 'name' => 'Angra dos Reis'],
            ['state_id' => 19, 'name' => 'Nova Friburgo'],
            ['state_id' => 19, 'name' => 'Barra Mansa'],
            ['state_id' => 19, 'name' => 'Teresópolis'],
            ['state_id' => 19, 'name' => 'Mesquita'],
            ['state_id' => 19, 'name' => 'Nilópolis'],

            // 20. Rio Grande do Norte (RN)
            ['state_id' => 20, 'name' => 'Natal'],
            ['state_id' => 20, 'name' => 'Mossoró'],
            ['state_id' => 20, 'name' => 'Parnamirim'],
            ['state_id' => 20, 'name' => 'São Gonçalo do Amarante'],
            ['state_id' => 20, 'name' => 'Macaíba'],
            ['state_id' => 20, 'name' => 'Ceará-Mirim'],
            ['state_id' => 20, 'name' => 'Caicó'],
            ['state_id' => 20, 'name' => 'Assu'],
            ['state_id' => 20, 'name' => 'Currais Novos'],
            ['state_id' => 20, 'name' => 'São José de Mipibu'],
            ['state_id' => 20, 'name' => 'Santa Cruz'],
            ['state_id' => 20, 'name' => 'Nova Cruz'],
            ['state_id' => 20, 'name' => 'Apodi'],
            ['state_id' => 20, 'name' => 'João Câmara'],
            ['state_id' => 20, 'name' => 'Canguaretama'],
            ['state_id' => 20, 'name' => 'Touros'],
            ['state_id' => 20, 'name' => 'Macau'],
            ['state_id' => 20, 'name' => 'Pau dos Ferros'],
            ['state_id' => 20, 'name' => 'Extremoz'],
            ['state_id' => 20, 'name' => 'Baraúna'],

            // 21. Rio Grande do Sul (RS)
            ['state_id' => 21, 'name' => 'Porto Alegre'],
            ['state_id' => 21, 'name' => 'Caxias do Sul'],
            ['state_id' => 21, 'name' => 'Canoas'],
            ['state_id' => 21, 'name' => 'Pelotas'],
            ['state_id' => 21, 'name' => 'Santa Maria'],
            ['state_id' => 21, 'name' => 'Gravataí'],
            ['state_id' => 21, 'name' => 'Viamão'],
            ['state_id' => 21, 'name' => 'Novo Hamburgo'],
            ['state_id' => 21, 'name' => 'São Leopoldo'],
            ['state_id' => 21, 'name' => 'Rio Grande'],
            ['state_id' => 21, 'name' => 'Alvorada'],
            ['state_id' => 21, 'name' => 'Passo Fundo'],
            ['state_id' => 21, 'name' => 'Sapucaia do Sul'],
            ['state_id' => 21, 'name' => 'Uruguaiana'],
            ['state_id' => 21, 'name' => 'Santa Cruz do Sul'],
            ['state_id' => 21, 'name' => 'Cachoeirinha'],
            ['state_id' => 21, 'name' => 'Bagé'],
            ['state_id' => 21, 'name' => 'Bento Gonçalves'],
            ['state_id' => 21, 'name' => 'Erechim'],
            ['state_id' => 21, 'name' => 'Guaíba'],

            // 22. Rondônia (RO)
            ['state_id' => 22, 'name' => 'Porto Velho'],
            ['state_id' => 22, 'name' => 'Ji-Paraná'],
            ['state_id' => 22, 'name' => 'Ariquemes'],
            ['state_id' => 22, 'name' => 'Vilhena'],
            ['state_id' => 22, 'name' => 'Cacoal'],
            ['state_id' => 22, 'name' => 'Rolim de Moura'],
            ['state_id' => 22, 'name' => 'Jaru'],
            ['state_id' => 22, 'name' => 'Guajará-Mirim'],
            ['state_id' => 22, 'name' => 'Machadinho d\'Oeste'],
            ['state_id' => 22, 'name' => 'Buritis'],
            ['state_id' => 22, 'name' => 'Pimenta Bueno'],
            ['state_id' => 22, 'name' => 'Ouro Preto do Oeste'],
            ['state_id' => 22, 'name' => 'Espigão d\'Oeste'],
            ['state_id' => 22, 'name' => 'Nova Mamoré'],
            ['state_id' => 22, 'name' => 'Candeias do Jamari'],
            ['state_id' => 22, 'name' => 'Alta Floresta d\'Oeste'],
            ['state_id' => 22, 'name' => 'Presidente Médici'],
            ['state_id' => 22, 'name' => 'Cujubim'],
            ['state_id' => 22, 'name' => 'São Francisco do Guaporé'],
            ['state_id' => 22, 'name' => 'Nova Brasilândia d\'Oeste'],

            // 23. Roraima (RR)
            ['state_id' => 23, 'name' => 'Boa Vista'],
            ['state_id' => 23, 'name' => 'Rorainópolis'],
            ['state_id' => 23, 'name' => 'Caracaraí'],
            ['state_id' => 23, 'name' => 'Pacaraima'],
            ['state_id' => 23, 'name' => 'Cantá'],
            ['state_id' => 23, 'name' => 'Mucajaí'],
            ['state_id' => 23, 'name' => 'Alto Alegre'],
            ['state_id' => 23, 'name' => 'Amajari'],
            ['state_id' => 23, 'name' => 'Bonfim'],
            ['state_id' => 23, 'name' => 'Normandia'],
            ['state_id' => 23, 'name' => 'Iracema'],
            ['state_id' => 23, 'name' => 'Uiramutã'],
            ['state_id' => 23, 'name' => 'Caroebe'],
            ['state_id' => 23, 'name' => 'São João da Baliza'],
            ['state_id' => 23, 'name' => 'São Luiz'],

            // 24. Santa Catarina (SC)
            ['state_id' => 24, 'name' => 'Joinville'],
            ['state_id' => 24, 'name' => 'Florianópolis'],
            ['state_id' => 24, 'name' => 'Blumenau'],
            ['state_id' => 24, 'name' => 'São José'],
            ['state_id' => 24, 'name' => 'Chapecó'],
            ['state_id' => 24, 'name' => 'Itajaí'],
            ['state_id' => 24, 'name' => 'Criciúma'],
            ['state_id' => 24, 'name' => 'Jaraguá do Sul'],
            ['state_id' => 24, 'name' => 'Palhoça'],
            ['state_id' => 24, 'name' => 'Lages'],
            ['state_id' => 24, 'name' => 'Balneário Camboriú'],
            ['state_id' => 24, 'name' => 'Brusque'],
            ['state_id' => 24, 'name' => 'Tubarão'],
            ['state_id' => 24, 'name' => 'São Bento do Sul'],
            ['state_id' => 24, 'name' => 'Camboriú'],
            ['state_id' => 24, 'name' => 'Caçador'],
            ['state_id' => 24, 'name' => 'Navegantes'],
            ['state_id' => 24, 'name' => 'Concórdia'],
            ['state_id' => 24, 'name' => 'Rio do Sul'],
            ['state_id' => 24, 'name' => 'Araranguá'],

            // 25. São Paulo (SP)
            ['state_id' => 25, 'name' => 'São Paulo'],
            ['state_id' => 25, 'name' => 'Guarulhos'],
            ['state_id' => 25, 'name' => 'Campinas'],
            ['state_id' => 25, 'name' => 'São Bernardo do Campo'],
            ['state_id' => 25, 'name' => 'Santo André'],
            ['state_id' => 25, 'name' => 'Osasco'],
            ['state_id' => 25, 'name' => 'Sorocaba'],
            ['state_id' => 25, 'name' => 'Ribeirão Preto'],
            ['state_id' => 25, 'name' => 'São José dos Campos'],
            ['state_id' => 25, 'name' => 'São José do Rio Preto'],
            ['state_id' => 25, 'name' => 'Mogi das Cruzes'],
            ['state_id' => 25, 'name' => 'Diadema'],
            ['state_id' => 25, 'name' => 'Jundiaí'],
            ['state_id' => 25, 'name' => 'Mauá'],
            ['state_id' => 25, 'name' => 'Piracicaba'],
            ['state_id' => 25, 'name' => 'Carapicuíba'],
            ['state_id' => 25, 'name' => 'Bauru'],
            ['state_id' => 25, 'name' => 'Itaquaquecetuba'],
            ['state_id' => 25, 'name' => 'São Vicente'],
            ['state_id' => 25, 'name' => 'Franca'],

            // 26. Sergipe (SE)
            ['state_id' => 26, 'name' => 'Aracaju'],
            ['state_id' => 26, 'name' => 'Nossa Senhora do Socorro'],
            ['state_id' => 26, 'name' => 'Lagarto'],
            ['state_id' => 26, 'name' => 'Itabaiana'],
            ['state_id' => 26, 'name' => 'São Cristóvão'],
            ['state_id' => 26, 'name' => 'Estância'],
            ['state_id' => 26, 'name' => 'Tobias Barreto'],
            ['state_id' => 26, 'name' => 'Simão Dias'],
            ['state_id' => 26, 'name' => 'Nossa Senhora da Glória'],
            ['state_id' => 26, 'name' => 'Poço Verde'],
            ['state_id' => 26, 'name' => 'Itabaianinha'],
            ['state_id' => 26, 'name' => 'Capela'],
            ['state_id' => 26, 'name' => 'Barra dos Coqueiros'],
            ['state_id' => 26, 'name' => 'Boquim'],
            ['state_id' => 26, 'name' => 'Nossa Senhora das Dores'],
            ['state_id' => 26, 'name' => 'Umbaúba'],
            ['state_id' => 26, 'name' => 'Poço Redondo'],
            ['state_id' => 26, 'name' => 'Canindé de São Francisco'],
            ['state_id' => 26, 'name' => 'Laranjeiras'],
            ['state_id' => 26, 'name' => 'Propriá'],

            // 27. Tocantins (TO)
            ['state_id' => 27, 'name' => 'Palmas'],
            ['state_id' => 27, 'name' => 'Araguaína'],
            ['state_id' => 27, 'name' => 'Gurupi'],
            ['state_id' => 27, 'name' => 'Porto Nacional'],
            ['state_id' => 27, 'name' => 'Paraíso do Tocantins'],
            ['state_id' => 27, 'name' => 'Colinas do Tocantins'],
            ['state_id' => 27, 'name' => 'Araguatins'],
            ['state_id' => 27, 'name' => 'Guaraí'],
            ['state_id' => 27, 'name' => 'Tocantinópolis'],
            ['state_id' => 27, 'name' => 'Formoso do Araguaia'],
            ['state_id' => 27, 'name' => 'Dianópolis'],
            ['state_id' => 27, 'name' => 'Augustinópolis'],
            ['state_id' => 27, 'name' => 'Miracema do Tocantins'],
            ['state_id' => 27, 'name' => 'Lagoa da Confusão'],
            ['state_id' => 27, 'name' => 'Pedro Afonso'],
            ['state_id' => 27, 'name' => 'São Miguel do Tocantins'],
            ['state_id' => 27, 'name' => 'Nova Olinda'],
            ['state_id' => 27, 'name' => 'Sítio Novo do Tocantins'],
            ['state_id' => 27, 'name' => 'Taguatinga'],
            ['state_id' => 27, 'name' => 'Xambioá'],
        ];

        // Add common fields to all records
        $cities = array_map(function ($city) use ($now) {
            return array_merge($city, [
                'country_id' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $cities);

        // Insert in chunks of 100 to avoid query limits
        foreach (array_chunk($cities, 100) as $chunk) {
            DB::table('cities')->insert($chunk);
        }
    }
}
