version: '3.8'

services:
  # MinIO Cluster - High Availability
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    environment:
      TZ: 'America/Sao_Paulo'
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'MinIO@SeuPassword2025!'
      MINIO_SERVER_URL: 'https://s3.webcarros.app.br'
      MINIO_BROWSER_REDIRECT_URL: 'https://minio.webcarros.app.br'
      # Configurações de performance
      MINIO_COMPRESS: 'true'
      MINIO_COMPRESS_EXTENSIONS: '.txt,.log,.csv,.json,.xml'
      MINIO_COMPRESS_MIME_TYPES: 'text/*,application/json,application/xml'

    volumes:
      - minio_data:/data

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
      labels:
        # API S3 (usado pelos sistemas)
        - "traefik.enable=true"
        - "traefik.http.routers.minio-api.rule=Host(`s3.webcarros.app.br`)"
        - "traefik.http.routers.minio-api.entrypoints=websecure"
        - "traefik.http.routers.minio-api.service=minio-api"
        - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
        - "traefik.http.routers.minio-api.tls.certresolver=le"
        - "traefik.http.routers.minio-api.middlewares=secure-headers"

        # Console Admin (interface web)
        - "traefik.http.routers.minio-console.rule=Host(`minio.webcarros.app.br`)"
        - "traefik.http.routers.minio-console.entrypoints=websecure"
        - "traefik.http.routers.minio-console.service=minio-console"
        - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
        - "traefik.http.routers.minio-console.tls.certresolver=le"
        - "traefik.http.routers.minio-console.middlewares=secure-headers"

        # Middleware de segurança
        - "traefik.http.middlewares.secure-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
        - "traefik.http.middlewares.secure-headers.headers.accesscontrolallowheaders=*"
        - "traefik.http.middlewares.secure-headers.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.middlewares.secure-headers.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.secure-headers.headers.addvaryheader=true"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - traefik_public

  # Backup automático do MinIO
  minio-backup:
    image: alpine:latest
    command: |
      sh -c "
        apk add --no-cache curl &&
        while true; do
          echo '[$(date)] Backup MinIO iniciado...' &&
          # Aqui você pode adicionar script de backup
          sleep 86400
        done
      "

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

    depends_on:
      - minio

    networks:
      - traefik_public

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/minio/data

networks:
  traefik_public:
    external: true
